apiVersion: v2
name: gotify
description: A Gotify Helm chart for Kubernetes
type: application
version: 6.0.1
# renovate: image=ghcr.io/gotify/server
appVersion: 2.7.3
dependencies:
  - name: common
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts
  - name: postgresql
    version: 16.7.27
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
