apiVersion: v2
name: slskd
description: An slskd Helm chart for Kubernetes
type: application
version: 0.8.4
# renovate: image=ghcr.io/slskd/slskd
appVersion: "0.24.0"
dependencies:
  - name: common
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts
