---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.4.0/charts/other/app-template/values.schema.json

controllers:
  main:
    # -- Set the controller upgrade strategy
    strategy: Recreate

    containers:
      # Configure the main application container
      slskd:
        image:
          # -- image repository
          repository: ghcr.io/slskd/slskd
          # -- image pull policy
          pullPolicy: IfNotPresent
          # -- image tag
          tag: 0.24.0

        # -- environment variables.
        # @default -- See [values.yaml](./values.yaml)
        env:
          SLSKD_REMOTE_CONFIGURATION: true
          SLSKD_REMOTE_FILE_MANAGEMENT: true

        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            memory: 1Gi

        probes:
          # -- Configures liveness probe
          liveness:
            type: HTTP
            path: /health
          # -- Configures readiness probe
          readiness:
            type: HTTP
            path: /health

      # Configure the gluetun sidecar
      gluetun:
        image:
          # -- image repository
          repository: qmcgaw/gluetun
          # -- image pull policy
          pullPolicy: IfNotPresent
          # -- image tag
          tag: v3.40.0

        # -- environment variables. [[ref]](https://github.com/qdm12/gluetun-wiki)
        # @default -- See [values.yaml](./values.yaml)
        env:
          VPN_TYPE: wireguard
          VPN_INTERFACE: wg0

        # Configure the container-specific securityContext
        securityContext:
          capabilities:
            add:
              - NET_ADMIN

# -- Configures service settings for the chart.
# @default -- See [values.yaml](./values.yaml)
service:
  main:
    controller: main
    ports:
      http:
        port: 5030
  soulseek:
    controller: main
    ports:
      tcp:
        port: 50300

# -- Configure the ServiceMonitors for the chart here.
# @default -- See [values.yaml](./values.yaml)
serviceMonitor:
  main:
    # -- Enables or disables the serviceMonitor.
    enabled: false
    serviceName: "{{ .Release.Name }}-main"
    # -- Configures the endpoints for the serviceMonitor. Helm templates can be used.
    # @default -- See [values.yaml](./values.yaml)
    endpoints:
      - port: http
        scheme: http
        path: /metrics

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    # tls:
    #   - secretName: chart-example.local-tls
    #     hosts:
    #       - chart-example.local

persistence:
  app:
    enabled: true
    accessMode: ReadWriteOnce
    size: 500Mi
    advancedMounts:
      main:
        slskd:
          - path: /app
    # storageClass: ""
