apiVersion: v2
name: ollama
description: An ollama Helm chart for Kubernetes
type: application
version: 3.0.12
# renovate: image=docker.io/ollama/ollama
appVersion: "0.12.11"
dependencies:
  - name: common
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts
