apiVersion: v2
name: jellyfin
description: A Jellyfin Helm chart for Kubernetes
type: application
version: 2.3.0
# renovate: image=ghcr.io/linuxserver/jellyfin
appVersion: "10.11.0"
dependencies:
  - name: common
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts
