{{/* Append the hardcoded settings */}}
{{- define "vaultwarden.harcodedValues" -}}
controllers:
  main:
    containers:
      main:
        env:
          {{- with .Values.ingress.main }}
          {{- if .enabled }}
          DOMAIN: http{{ if .tls }}s{{ end }}://{{ (first .hosts).host }}
          {{- end }}
          {{- end }}

          ROCKET_PORT: {{ quote .Values.service.main.ports.http.port }}
{{- end -}}
{{- $_ := merge .Values (include "vaultwarden.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.all" . }}