apiVersion: v2
name: lidarr
description: A Lidarr Helm chart for Kubernetes
type: application
version: 1.1.0
# renovate: image=ghcr.io/linuxserver/lidarr
appVersion: "3.1.0.4875-ls11"
dependencies:
  - name: common
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts
