apiVersion: v2
name: paperless
description: A Paperless Helm chart for Kubernetes
type: application
version: 2.4.0
# renovate: image=ghcr.io/paperless-ngx/paperless-ngx
appVersion: 2.19.5
dependencies:
  - name: common
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts
  - name: tika
    version: 3.2.2
    repository: https://apache.jfrog.io/artifactory/tika
    condition: tika.enabled
  - name: gotenberg
    version: 1.13.0
    repository: https://maikumori.github.io/helm-charts
    condition: gotenberg.enabled
