apiVersion: v2
name: paperless
description: A Paperless Helm chart for Kubernetes
type: application
version: 0.1.5
# renovate: image=ghcr.io/paperless-ngx/paperless-ngx
appVersion: 2.19.5
dependencies:
  - name: common
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts
