apiVersion: v2
name: flaresolverr
description: A Flaresolverr Helm chart for Kubernetes
type: application
version: 0.4.10
# renovate: image=ghcr.io/flaresolverr/flaresolverr
appVersion: "v3.4.5"
dependencies:
  - name: common
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts
