{{- if not .Values.webui.auth.disabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-webui-user
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  username: {{ .Values.webui.auth.user | default "admin" | b64enc | quote }}
  password: {{ .Values.webui.auth.password | default "" | b64enc | quote }}
---
{{- if .Values.webui.auth.jwt_key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jwt-secret
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  secret-key: {{ .Values.webui.auth.jwt_key | b64enc | quote }}
{{- end }}
{{- end }}
---
{{- if and .Values.soulseek.user .Values.soulseek.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-slsk-user
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  username: {{ .Values.soulseek.user | b64enc | quote }}
  password: {{ .Values.soulseek.password | b64enc | quote }}
{{- end }}