apiVersion: v2
name: jellyseerr
description: A Jellyseerr Helm chart for Kubernetes
type: application
version: 1.2.0
# renovate: image=docker.io/fallenbagel/jellyseerr
appVersion: "2.7.3"
dependencies:
  - name: common
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts
