apiVersion: v2
name: navidrome
description: A Navidrome chart for Kubernetes
type: application
version: 1.0.0
# renovate: image=deluan/navidrome
appVersion: "0.58.5"
dependencies:
  - name: common
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts
