apiVersion: v2
name: cloudflared
description: A cloudflared Helm chart for Kubernetes
type: application
version: 1.1.0
# renovate: image=docker.io/cloudflare/cloudflared
appVersion: "2025.11.1"
dependencies:
  - name: common
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts
