apiVersion: v2
name: vaultwarden
description: A Vaultwarden Helm chart for Kubernetes
type: application
version: 1.0.0
# renovate: image=ghcr.io/dani-garcia/vaultwarden
appVersion: "1.34.3"
dependencies:
  - name: common
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts
