apiVersion: v2
name: prowlarr
description: A Prowlarr Helm chart for Kubernetes
type: application
version: 2.1.0
# renovate: image=ghcr.io/linuxserver/prowlarr
appVersion: "2.3.0.5236-ls132"
dependencies:
  - name: common
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts
